name: building .net application
on:
  push:
jobs:
  build_dot_net:
    runs-on: ubuntu-latest
    steps:
      - name: setup dotnet SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: checkout your source
        uses: actions/checkout@v3

      - name: list your repo
        run: ls -l 
